apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-email-worker
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: email-worker
spec:
  type: {{ .Values.service.emailWorker.type }}
  ports:
    - port: {{ .Values.service.emailWorker.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: email-worker
