{{- if and .Values.externalSecrets.enabled (.Capabilities.APIVersions.Has "external-secrets.io/v1beta1") }}
apiVersion: {{ .Values.externalSecrets.apiVersion }}
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-database
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name | quote }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind | quote }}
  target:
    name: {{ .Values.app.database.secretName | quote }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.app.database.secretKey | quote }}
      remoteRef:
        key: {{ .Values.externalSecrets.database.remoteRef.key | quote }}
        property: {{ .Values.externalSecrets.database.remoteRef.property | quote }}
---
apiVersion: {{ .Values.externalSecrets.apiVersion }}
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-postgres
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name | quote }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind | quote }}
  target:
    name: {{ .Values.postgres.auth.passwordSecretName | quote }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.postgres.auth.passwordSecretKey | quote }}
      remoteRef:
        key: {{ .Values.externalSecrets.postgresPassword.remoteRef.key | quote }}
        property: {{ .Values.externalSecrets.postgresPassword.remoteRef.property | quote }}
---
apiVersion: {{ .Values.externalSecrets.apiVersion }}
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-keycloak
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreRef.name | quote }}
    kind: {{ .Values.externalSecrets.secretStoreRef.kind | quote }}
  target:
    name: {{ .Values.keycloak.database.passwordSecretName | quote }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.keycloak.database.passwordSecretKey | quote }}
      remoteRef:
        key: {{ .Values.externalSecrets.keycloakPostgresPassword.remoteRef.key | quote }}
        property: {{ .Values.externalSecrets.keycloakPostgresPassword.remoteRef.property | quote }}
    - secretKey: {{ .Values.keycloak.auth.passwordSecretKey | quote }}
      remoteRef:
        key: {{ .Values.externalSecrets.keycloakAdminPassword.remoteRef.key | quote }}
        property: {{ .Values.externalSecrets.keycloakAdminPassword.remoteRef.property | quote }}
{{- end }}
