{{- if and .Values.secrets.create .Values.secrets.keycloakAdminPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.keycloak.auth.adminPasswordSecretName }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  {{ .Values.keycloak.auth.adminPasswordSecretKey }}: {{ .Values.secrets.keycloakAdminPassword | quote }}
{{- end }}
{{- if and .Values.secrets.create .Values.secrets.keycloakPostgresPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.keycloak.postgres.passwordSecretName }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
stringData:
  {{ .Values.keycloak.postgres.passwordSecretKey }}: {{ .Values.secrets.keycloakPostgresPassword | quote }}
{{- end }}
